#!/usr/bin/env python
import time
import rospy
import actionlib
from control_msgs.msg import *
from trajectory_msgs.msg import *

JOINT_NAMES = ['shoulder_pan_joint', 'shoulder_lift_joint', 'elbow_joint',
               'wrist_1_joint', 'wrist_2_joint', 'wrist_3_joint','bh_j32_joint','bh_j33_joint','bh_j11_joint','bh_j12_joint','bh_j13_joint','bh_j21_joint','bh_j22_joint','bh_j23_joint']
Q1 = [-1.57,0,0,-1.57,0,0,-1.57,0,0,-1.57,0,0,0,0]
Q2 = [-1.57,-1.57,0,-1.57,0,0,-1.57,-1.57,0,-1.57,0,0,0,0]




client = None

def move():
    g = FollowJointTrajectoryGoal()
    g.trajectory = JointTrajectory()
    g.trajectory.joint_names = JOINT_NAMES
    g.trajectory.points = [
        JointTrajectoryPoint(positions=Q1, velocities=[0]*6, time_from_start=rospy.Duration(6.0)),
        JointTrajectoryPoint(positions=Q2, velocities=[0]*6, time_from_start=rospy.Duration(12.0))]
    client.send_goal(g)

    

    try:
        client.wait_for_result()
    except KeyboardInterrupt:
        client.cancel_goal()
        raise




def main():
    global client
    try:
        rospy.init_node("test_move", anonymous=True, disable_signals=True)
        client = actionlib.SimpleActionClient('arm_controller/follow_joint_trajectory', FollowJointTrajectoryAction)
        print "Waiting for ur5_arm server..."
        client.wait_for_server()
        print "Connected to ur5_arm server"
        move()
    except KeyboardInterrupt:
        rospy.signal_shutdown("KeyboardInterrupt")
        raise

if __name__ == '__main__': main()

